### PR TITLE
Fixed client source

### PR DESCRIPTION
**Pull request by ghost**
put me out of my misery already, jesus. and quit coding kotlin. JESUS.

### CODE REVIEW

**Comment by monochandev** [comment]
+1, LGTM!

**Comment by RoootTheFox** [comment]
LGTM 🔥

**Comment by weedgirl68** [comment]
LGTM :shipit:

**Comment by ziIIas** [comment]
@twenty48lol LGTM, push

**Comment by SmallSmallXD** [comment]
LGTM

**Comment by oliking800** [comment]
LGTM

**Comment by vsynthetic** [comment]
LGTM

**Comment by InfiniteCod3** [comment]
LGTM, push when?

**Comment by OfficialError** [comment]
LGTM

**Comment by Blexyel** [comment]
+1 LGTM 👍🏻

**Comment by twenty48lol** [comment]
yes.

**Comment by zerlokker** [comment]
Come on man merge this shit

**Pull request closed without merging**
